name: Main branch CI

on:
  pull_request:
    branches:
      - main
  push:
  schedule:
    - cron: '40 6 * * 0'

jobs:
  check-libraries:
    uses: canonical/sdcore-github-workflows/.github/workflows/check-libraries.yaml@v1.0.0
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

  lint-report:
    uses: canonical/sdcore-github-workflows/.github/workflows/lint-report.yaml@v1.0.0

  static-analysis:
    uses: canonical/sdcore-github-workflows/.github/workflows/static-analysis.yaml@v1.0.0

  unit-tests-with-coverage:
    uses: canonical/sdcore-github-workflows/.github/workflows/unit-test.yaml@v1.0.0

  build:
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 5.20/stable

      - name: Install charmcraft
        run: sudo snap install charmcraft --channel=edge --classic

      - name: Build charm under test
        run: charmcraft pack --verbose

      - name: Archive Charm Under Test
        uses: actions/upload-artifact@v4
        with:
          name: built-charm
          path: "*.charm"
          retention-days: 5

  integration-test:
    needs:
      - build
    uses: ./.github/workflows/integration-tests.yaml

  publish-charm:
    name: Publish Charm
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
    if: ${{ github.ref_name == 'main' }}
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-charm.yaml@v1.0.0
    with:
      track-name: 1.4
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

  publish-charm-on-push:
    name: Publish Developer Charm To Branch
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
    if: ${{ (github.ref_name != 'main') && (github.event_name == 'push') }}
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-charm.yaml@v1.0.0
    with:
      branch-name: ${{ github.ref_name }}
      track-name: 1.4
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
