name: Main branch CI

on:
  pull_request:
    branches:
      - main
  push:
  schedule:
    - cron: '40 6 * * 0'

jobs:
  check-libraries:
    uses: canonical/sdcore-github-workflows/.github/workflows/check-libraries.yaml@v2.2.0
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

  lint-report:
    uses: canonical/sdcore-github-workflows/.github/workflows/lint-report.yaml@v2.2.0

  static-analysis:
    uses: canonical/sdcore-github-workflows/.github/workflows/static-analysis.yaml@v2.2.0

  unit-tests-with-coverage:
    uses: canonical/sdcore-github-workflows/.github/workflows/unit-test.yaml@v2.2.0

  build:
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
    uses: canonical/sdcore-github-workflows/.github/workflows/build.yaml@v2.3.0
    secrets: inherit

  integration-test:
    needs:
      - build
    uses: ./.github/workflows/integration-tests.yaml

  publish-charm:
    name: Publish Charm
    runs-on: ubuntu-22.04
    if: ${{ github.ref_name == 'main' }}
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Tested Charm
        uses: actions/download-artifact@v4
        with:
          name: built-charm

      - name: Get Charm Under Test Path
        id: charm-path
        run: echo "charm_path=$(find . -name '*.charm' -type f -print)" >> $GITHUB_OUTPUT

      - name: Install charmcraft
        run: sudo snap install charmcraft --classic --channel=edge

      - name: Upload charm to Charmhub
        uses: canonical/charming-actions/upload-charm@934193396735701141a1decc3613818e412da606
        with:
          built-charm-path: ${{ steps.charm-path.outputs.charm_path }}
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: 1.4/edge

      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log

  publish-charm-on-push:
    name: Publish Developer Charm To Branch
    runs-on: ubuntu-22.04
    if: ${{ (github.ref_name != 'main') && (github.event_name == 'push') }}
    permissions:
      contents: write
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Tested Charm
        uses: actions/download-artifact@v4
        with:
          name: built-charm

      - name: Get Charm Under Test Path
        id: charm-path
        run: echo "charm_path=$(find . -name '*.charm' -type f -print)" >> $GITHUB_OUTPUT

      - name: Install charmcraft
        run: sudo snap install charmcraft --classic --channel=edge

      - name: Sanitize the branch variable
        id: sanitize
        run: |
          echo sanitized=$(echo ${{ github.ref_name }} | sed 's/[/_.]/-/g' | sed "s/^/\//") >> $GITHUB_OUTPUT
        if: ${{ github.ref_name != '' }}

      - name: Upload charm to Charmhub
        uses: canonical/charming-actions/upload-charm@934193396735701141a1decc3613818e412da606
        with:
          built-charm-path: ${{ steps.charm-path.outputs.charm_path }}
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: 1.4/edge${{ steps.sanitize.outputs.sanitized }}

      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log
